// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3694.TShirtCannon;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController chassisLeftDrive;
    public static SpeedController chassisRightDrive;
    public static RobotDrive chassisRobotDrive21;
    public static Compressor cannonCompressor1;
    public static Compressor cannonCompressor2;
    public static Solenoid cannonSolenoid1;
    public static Solenoid cannonSolenoid2;
    public static Solenoid cannonSolenoid3;
    public static Solenoid cannonSolenoid4;
    public static Ultrasonic cannonUltrasonic;
    public static SpeedController turretTurnMotor;
    public static SpeedController turretElevationMotor;
    public static DigitalInput turretTurnSwitch1;
    public static DigitalInput turretTurnSwitch2;
    public static DigitalInput turretElevationSwitch1;
    public static DigitalInput turretElevationSwitch2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisLeftDrive = new Victor(0);
        LiveWindow.addActuator("Chassis", "LeftDrive", (Victor) chassisLeftDrive);
        
        chassisRightDrive = new Victor(1);
        LiveWindow.addActuator("Chassis", "RightDrive", (Victor) chassisRightDrive);
        
        chassisRobotDrive21 = new RobotDrive(chassisLeftDrive, chassisRightDrive);
        
        chassisRobotDrive21.setSafetyEnabled(true);
        chassisRobotDrive21.setExpiration(0.1);
        chassisRobotDrive21.setSensitivity(0.5);
        chassisRobotDrive21.setMaxOutput(1.0);

        cannonCompressor1 = new Compressor(0);
        
        
        cannonCompressor2 = new Compressor(1);
        
        
        cannonSolenoid1 = new Solenoid(0, 0);
        LiveWindow.addActuator("Cannon", "Solenoid 1", cannonSolenoid1);
        
        cannonSolenoid2 = new Solenoid(0, 1);
        LiveWindow.addActuator("Cannon", "Solenoid 2", cannonSolenoid2);
        
        cannonSolenoid3 = new Solenoid(0, 2);
        LiveWindow.addActuator("Cannon", "Solenoid 3", cannonSolenoid3);
        
        cannonSolenoid4 = new Solenoid(0, 3);
        LiveWindow.addActuator("Cannon", "Solenoid 4", cannonSolenoid4);
        
        cannonUltrasonic = new Ultrasonic(4, 5);
        LiveWindow.addSensor("Cannon", "Ultrasonic", cannonUltrasonic);
        
        turretTurnMotor = new Victor(2);
        LiveWindow.addActuator("Turret", "TurnMotor", (Victor) turretTurnMotor);
        
        turretElevationMotor = new Victor(3);
        LiveWindow.addActuator("Turret", "ElevationMotor", (Victor) turretElevationMotor);
        
        turretTurnSwitch1 = new DigitalInput(0);
        LiveWindow.addSensor("Turret", "TurnSwitch1", turretTurnSwitch1);
        
        turretTurnSwitch2 = new DigitalInput(1);
        LiveWindow.addSensor("Turret", "TurnSwitch2", turretTurnSwitch2);
        
        turretElevationSwitch1 = new DigitalInput(2);
        LiveWindow.addSensor("Turret", "ElevationSwitch1", turretElevationSwitch1);
        
        turretElevationSwitch2 = new DigitalInput(3);
        LiveWindow.addSensor("Turret", "ElevationSwitch2", turretElevationSwitch2);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
